include_role 'base'

include_cookbook 'eza'
include_cookbook 'starship'
include_cookbook 'vim'
include_cookbook 'tmux'
include_cookbook 'git'
include_cookbook 'fish'
include_cookbook 'zellij'
include_cookbook '1Password'

# cli tools(not use brew)
include_cookbook 'cli/bat'
include_cookbook 'cli/bctx'
include_cookbook 'cli/direnv'
include_cookbook 'cli/dlayer'
include_cookbook 'cli/fd'
include_cookbook 'cli/fzf'
include_cookbook 'cli/gh'
# include_cookbook 'cli/ghq'
include_cookbook 'cli/hyperfine'
include_cookbook 'cli/jq'
include_cookbook 'cli/mitamae'
include_cookbook 'cli/pet'
include_cookbook 'cli/ripgrep'
include_cookbook 'cli/vegeta'
include_cookbook 'cli/watchexec'

include_cookbook 'go'
include_cookbook 'nodejs'
include_cookbook 'rust'
include_cookbook 'ruby'

# go tools
include_cookbook 'cli/cobra'
include_cookbook 'cli/ujsonize'
include_cookbook 'cli/usql'
