[character]
success_symbol = "Œª"
error_symbol = "Œª"

[aws]
disabled = false
format = '[$symbol($profile )(\($region\) )]($style)'
style = "bold red"
[aws.region_aliases]
ap-northeast-1 = "tokyo"

[gcloud]
disabled = false
format = '[$symbol\($active\)]($style) '

[gcloud.region_aliases]
asia-northeast1 = 'tokyo'

[rust]
format = '[$symbol($version )]($style)'

[golang]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
format = '[$symbol($version )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[docker_context]
format = "[üêã $context](blue bold)"

[nix_shell]
impure_msg = '[impure](bold red)'
pure_msg = '[pure](bold green)'
format = '[‚òÉÔ∏è $state( \($name\))](bold blue) '

[cmd_duration]
disabled = true

[status]
disabled = false