# syntax 関連{{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'LnL7/vim-nix'
on_ft = 'nix'
# }}}

# テキストを囲うものを編集
[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

# 括弧関連{{{
# 括弧を自動で閉じて、改行時にインデント
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_post_source = '''
call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': '{', 'input': '{'})'
'''

# do endなどの中括弧{}以外で対応するものを自動入力
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
# }}}

# vim:set foldmethod=marker:
