include_role 'base'

include_cookbook 'brew'
brew 'pkg-config'
brew 'coreutils'
brew 'moreutils'
brew 'gnuplot'
brew 'gnupg'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'htop'
brew 'mkcert'
brew 'protobuf'
brew 'qemu'

include_cookbook 'fish'
include_cookbook 'starship'
include_cookbook 'vim'
include_cookbook 'emacs'
include_cookbook 'tmux'
include_cookbook 'multipass'
include_cookbook 'git'

# cli tools(not use brew)
include_cookbook 'cli/direnv'
include_cookbook 'cli/fzf.rb'
include_cookbook 'cli/gh'
include_cookbook 'cli/ghq'
include_cookbook 'cli/jq'
include_cookbook 'cli/ripgrep'
include_cookbook 'cli/vegeta'
include_cookbook 'cli/dlayer'
include_cookbook 'cli/bctx'
include_cookbook 'cli/bat'
include_cookbook 'cli/fd'
include_cookbook 'cli/hyperfine'

# lang
include_cookbook 'nodejs'
include_cookbook 'rust'
include_cookbook 'ruby'