import = [
  "~/.config/alacritty/themes/themes/pencil_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal.family = "0xProto Nerd Font Mono"
normal.style = "Regular"
bold.family = "0xProto Nerd Font Mono"
bold.style = "Bold"
italic.family = "0xProto Nerd Font Mono"
italic.style = "Italic"
size = 17.0

[window]
opacity = 0.95
padding.x = 10
padding.y = 10
decorations = "Buttonless"
blur = true
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

